# Generated by Django 3.2.15 on 2022-10-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artiste',
        ),
    ]
