# Generated by Django 3.2.15 on 2022-10-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20221025_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artiste',
        ),
    ]
