# Generated by Django 3.2.15 on 2022-11-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_auto_20221025_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='artiste_id',
        ),
    ]
